### ISSUE TITLE
I can not download pictures 

### ISSUE THREAD

**Issue by nazhendenb** [tetrix1993/hitomi-downloader#1]
The galleries URL: https://hitomi.la/galleries/1460510.html
COMMAND:  python hitomi_downloader.py 1549920 30 140
OUTPUT : 
Traceback (most recent call last):
  File "hitomi_downloader.py", line 129, in <module>
    run()
  File "hitomi_downloader.py", line 105, in run
    image_links = get_image_links()
  File "hitomi_downloader.py", line 78, in get_image_links
    name = split1[i].split('"name":"')[1].split('"')[0]
IndexError: list index out of range

**Comment by tetrix1993** [comment]
Hi, try running hitomi_download_2.py instead i.e.: python hitomi_download_2.py 1549920 30 140

**Comment by nazhendenb** [comment]
> Hi, try running hitomi_download_2.py instead i.e.: python hitomi_download_2.py 1549920 30 140

Thanks for replying, hitomi_download_2.py can download them, but per picture just has 200kb and the format is webp. It is perfect if this script can download higher resolution such as PNG

**Comment by tetrix1993** [comment]
> > Hi, try running hitomi_download_2.py instead i.e.: python hitomi_download_2.py 1549920 30 140
> 
> Thanks for replying, hitomi_download_2.py can download them, but per picture just has 200kb and the format is webp. It is perfect if this script can download higher resolution such as PNG

True, but having smaller size is advantageous especially if there is lack of storage space and higher resolution is not needed (e.g. viewing from a smartphone).

I may update the script to download higher resolution when I have the time.
